---
application:
  name: "geo-server"
  project: "geo-server"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "geo"
  version: "4.4"
routers:
- name: "main-geo-server"
  routes:
  - application_name: "geo-server"
    paths:
    - "/*"
